 File "/home/kali/Desktop/iotcar.py", line 10, in <module>
    conn = mariadb.connect(
  File "/home/kali/.local/lib/python3.9/site-packages/mysql/connector/pooling.py", line 323, in connect
    return MySQLConnection(*args, **kwargs)
  File "/home/kali/.local/lib/python3.9/site-packages/mysql/connector/connection.py", line 185, in __init__
    self.connect(**kwargs)
  File "/home/kali/.local/lib/python3.9/site-packages/mysql/connector/abstracts.py", line 1605, in connect
    self._open_connection()
  File "/home/kali/.local/lib/python3.9/site-packages/mysql/connector/connection.py", line 411, in _open_connection
    raise err
  File "/home/kali/.local/lib/python3.9/site-packages/mysql/connector/connection.py", line 388, in _open_connection
    self._do_auth(
  File "/home/kali/.local/lib/python3.9/site-packages/mysql/connector/connection.py", line 320, in _do_auth
    ok_pkt = self._authenticator.authenticate(
  File "/home/kali/.local/lib/python3.9/site-packages/mysql/connector/authentication.py", line 381, in authenticate
    ok_pkt = self._handle_server_response(sock, pkt)
  File "/home/kali/.local/lib/python3.9/site-packages/mysql/connector/authentication.py", line 287, in _handle_server_response
    raise get_exception(pkt)
mysql.connector.errors.ProgrammingError: 1698 (28000): Access denied for user 'root'@'localhost'
